### ISSUE TITLE
번역 주의사항

### ISSUE THREAD

**Issue by pulp-pixel** [envybros/book-cpp#1]
최대한 읽기 쉽게 해야함
진짜 내가 보기에 하나라도 어색한 문장이 있으면 안됨
저 튜토리얼의 모든 문장이 이해하기 쉬워야해. 

저거 다 번역하고 나면, 검토 작업 할 것
그리고 이미지도 수정해보고, 바뀐 사항 있으면 적용. 

검수 작업 이후 배포

그리고 나서 운영체제랑 네트워크, 자료구조, 알고리즘 등등 하면 될듯

병렬적으로 Vulkan 튜토리얼 번역
C++부터 이해하고 드가야 나도 더 잘할듯

3D 프로그래밍 내용도 추가하기 (선형대수)

**Comment by pablo-stelsi** [comment]
Title도 # 하나로 가야할 것 같은데.. 제목 글자 너무 작음

**Comment by pulp-pixel** [comment]
이거 깃북 말고 자체 웹사이트 내로 들어가는 편이 더 나을듯..
너무 안예쁨
